### ISSUE TITLE
Generated runbook by `runn new` for a gRPC method which need empty message seems invalid

### ISSUE THREAD

**Issue by kyu08** [k1LoW/runn#1009]
Thanks for maintaining great tool! Also, [`runn クックブック`](https://zenn.dev/k1low/books/runn-cookbook/viewer/about) you wrote is very helpful for me.

## Premise
The rpc method I want to test is this:
```proto
service MyService {
  rpc Health (HealthRequest) returns (HealthResponse);
}

message HealthRequest {}

message HealthResponse {
  string message = 1;
}
```

## Issue
When I tried to generate a runbook by `runn new -- grpcurl -plaintext localhost:8080 myApp.MyService/Health` for the gRPC method above, `runn` generated the following runbook:
```yaml
runners:
  greq: grpc://localhost:8080
steps:
- greq:
    myApp.MyService/Health: {}
```

Then I wrote above content to `./e2e/health.yaml`, and run `runn run --grpc-no-tls e2e/health.yaml`.

The output was:

```sh
  Failure/Error: gRPC request failed on "Generated by `runn new`".steps[0]: unary RPC message should be 1
  Failure step (e2e/health.yaml):
  4 - greq:
  5     myApp.MyService/Health: {}


1 scenario, 0 skipped, 1 failure
```

When I fix a part of yaml like this:
```yaml
    # Before
    myApp.MyService/Health: {}
    # After
    myApp.MyService/Health:
      message: {}
```

The test has passed:
```sh
.

1 scenario, 0 skipped, 0 failures
```

## Solution I suppose
The runbook of `runn new` for a method which needs empty message may be changed.

I tried to fix this problem. #1010. 
I'm new to gRPC and runn. So if I miss something or misunderstand, please let me know. 🙇
