### ISSUE TITLE
[Question] How does the --fail-fast option affect the runn run behavior?

### ISSUE THREAD

**Issue by h6ah4i** [k1LoW/runn#1032]
I expected the book `3.yaml` not to run when the `--fail-fast` option is specified in the following setup. However, the command output shows that the book `3.yaml` is still being evaluated. Am I misunderstanding how this command-line option works?

```bash
❯ runn run --fail-fast './*.yaml'
.F.

1) 2.yaml 5a1a25bd510cabac2c55504c9f80759ca4ca935b
  Failure/Error: test failed on "[No Description]".steps.forceFail: condition is not true

  Condition:
    false

    │

Error: step not found: 0
```

---

### 1.yaml
```yaml
steps:
  forcePass:
    test: |
      true
```

### 2.yaml
```yaml
steps:
  forceFail:
    test: |
      false
```

### 3.yaml
```yaml
steps:
  forcePass:
    test: |
      true
```
