### ISSUE TITLE
Ignore fields when compare test

### ISSUE THREAD

**Issue by hungpk-bap** [k1LoW/runn#1047]
I'm using a YAML format to define test cases and running a compare command in Go like this:

```yaml
compare(current.res.message, vars.response, vars.ignoreField)
```
I’ve tried defining ignoreField in two different ways:

As a string:

```yaml
vars:
  ignoreField: "field1, field2"
```
As a list:

```yaml
vars:
  ignoreField:
    - field1
    - field2
```
Results:

In case 1, Go interprets the entire string ```("field1, field2")``` as a single parameter, which is not the desired behavior.
In case 2, I get an error: cannot use []interface{} as type string.
The compare function works fine if I declare ignoreField as a single value. However, when I try to ignore multiple fields, it doesn't work.

**My Proposal:**
I’m thinking about modifying the ```compare``` function to accept ```[]string``` instead of ```...string``` (variadic string parameters) to handle a list of fields.

Could you please provide feedback on this approach or suggest a better solution?

**Comment by hankphan-dev** [comment]
I'm also having this problem when trying to ignore multiple fields in the response when comparing

**Comment by hankphan-dev** [comment]
Looks seem you want use 
```yml
compare(current.res.message, vars.response, vars.ignoreField) 
```
for multiple scenarios?
Can you try applying a comparison command to each scenario? Because you have to pass a list of arguments to that command instead of passing an argument vars.ignoreField containing the values of the fields separated by commas
```yml
Scenario 1: (ignore 2 field)
compare(current.res.message, vars.response, vars.ignoreField[0], vars.ignoreField[1]) 

Scenario 2: (ignore 3 field)
compare(current.res.message, vars.response, vars.ignoreField[0], vars.ignoreField[1], vars.ignoreField[2]) 
```
It works with me
