### ISSUE TITLE
[bug]The leading zero in the request body variable disappears.

### ISSUE THREAD

**Issue by Rayleigh865** [k1LoW/runn#1085]
I always appreciate your support. I have discovered a bug-like behavior in Runn version 0.122.0 and am submitting an issue about it. When executing a yml file as outlined below, the leading zero in the request body disappears. Specifically, mobile1 is sent in the request as 90, not 090. Could you please check this issue? It looks like the problem is due to the conversion of a string type to a number type.

```
desc: check bug
runners:
  hoge:
    endpoint: http://localhost:3000
steps:
  sample:
    hoge:
      /api/hoge:
        post:
          body:
            application/json:
              mobile1: "090"
              mobile2: "1234"
              mobile3: "5678"
              code: "090"
              sample: "0123456789"
              sample2: "123456789"
    test: current.res.status == 200
```

When executed in debug, the log is as follows:

```
$ runn run tests/sample.yml --debug
Run "hoge" on "check bug".steps.sample
-----START HTTP REQUEST-----
POST /api/hoge HTTP/1.1
Host: localhost:3000
Content-Type: application/json

{"code":90,"mobile1":90,"mobile2":"1234","mobile3":"5678","sample":123456789,"sample2":"123456789"}
-----END HTTP REQUEST-----
F

1) tests/sample.yml a4a31011c3cbb49e8c6cea038a0ad5706e84399c
  Failure/Error: http request failed on "check bug".steps.sample: Post "http://localhost:3000/api/hoge": dial tcp [::1]:3000: connect: connection refused
  Failure step (tests/sample.yml):
   6   sample:
   7     hoge:
   8       /api/hoge:
   9         post:
  10           body:
  11             application/json:
  12               mobile1: "090"
  13               mobile2: "1234"
  14               mobile3: "5678"
  15               code: "090"
  16               sample: "0123456789"
  17               sample2: "123456789"
  18     test: current.res.status == 200


1 scenario, 0 skipped, 1 failure
```
