### ISSUE TITLE
Support a feature that interrupts when the result of a command execution fails

### ISSUE THREAD

**Issue by karrybit** [k1LoW/runn#1090]
Even if the exec command fails, the subsequent steps are still executed. The minimal reproduction setup is as follows.

<details>
<summary>minimal reproduction</summary>

```yaml
steps:
  exit_1:
    exec:
      command: exit 1
      shell: bash
      liveOutput: true
  exit_1_and_test:
    exec:
      command: exit 1
      shell: bash
      liveOutput: true
      test: current.exit_code == 0
  exit_1_and_set:
    exec:
      command: |
        set -euo pipefail
        exit 1
      shell: bash
      liveOutput: true
  exit_1_and_set_and_test:
    exec:
      command: |
        set -euo pipefail
        exit 1
      shell: bash
      liveOutput: true
      test: current.exit_code == 0
```
```
❯ runn --version                                        
runn version 0.122.1

❯ runn run test.yaml --scopes run:exec --verbose --debug
=== [No Description] (test.yaml)
Run "exec" on "[No Description]".steps.exit_1
-----START COMMAND-----
exit 1
-----END COMMAND-----
-----START STDOUT-----

-----END STDOUT-----
-----START STDERR-----

-----END STDERR-----
    --- (exit_1) ... ok

Run "exec" on "[No Description]".steps.exit_1_and_test
-----START COMMAND-----
exit 1
-----END COMMAND-----
-----START STDOUT-----

-----END STDOUT-----
-----START STDERR-----

-----END STDERR-----
    --- (exit_1_and_test) ... ok

Run "exec" on "[No Description]".steps.exit_1_and_set
-----START COMMAND-----
set -euo pipefail
exit 1
-----END COMMAND-----
-----START STDOUT-----

-----END STDOUT-----
-----START STDERR-----

-----END STDERR-----
    --- (exit_1_and_set) ... ok

Run "exec" on "[No Description]".steps.exit_1_and_set_and_test
-----START COMMAND-----
set -euo pipefail
exit 1
-----END COMMAND-----
-----START STDOUT-----

-----END STDOUT-----
-----START STDERR-----

-----END STDERR-----
    --- (exit_1_and_set_and_test) ... ok


1 scenario, 0 skipped, 0 failures
```

</details>

Additionally, could you consider supporting a feature to easily configure shell option like `set -euo pipefail`?
The reference article is as follows.
- https://taskfile.dev/usage/#set-and-shopt
- https://zenn.dev/shunsuke_suzuki/scraps/172683d8bad652
