### ISSUE TITLE
Ensure a means of accessing the current step variable

### ISSUE THREAD

**Issue by k2tzumi** [k1LoW/runn#113]
refs https://github.com/k1LoW/runn/pull/97#discussion_r950659660

# Proposal

If the request and test are executed in the same step, we want easy access to the response results.

Define the `current` variable so that it can be accessed by the same variable name in the named and unnamed steps.

```yaml
steps:
  -
    req:
      /get?var=foo:
        get:
          body: null
    test: |
      current.res.status == 200
```

```yaml
steps:
  reqget:
    req:
      /get?var=foo:
        get:
          body: null
    test: |
      current.res.status == 200
```
