### ISSUE TITLE
"loop: 0" gives "failed to record: store.stepMapKeys is zero" error

### ISSUE THREAD

**Issue by h6ah4i** [k1LoW/runn#1144]
Hi, is this behavior intended? I think it would be more convenient to just skip the step if the loop count is zero.

```yaml
# hello.yaml
vars:
  hello: "hello"

steps:
  hello:
    loop: 0
    dump: vars.hello
```

```bash
❯ runn run hello.yaml
F

1) hello.yaml f867c113c092691380b75e3e1a5fdf463bce15e4
  Failure/Error: failed to record: store.stepMapKeys is zero

1 scenario, 0 skipped, 1 failure
```
