### ISSUE TITLE
`runn loadt` gets stuck on GitHub Actions

### ISSUE THREAD

**Issue by mi-wada** [k1LoW/runn#1149]
## Problem

When running `runn loadt` on GitHub Actions, it doesn't finish. Therefore it meets GitHub Actions timeout, and fail CI. I tried on `ubuntu-latest` and `macos-latest`, same results.
exec log: https://github.com/mi-wada/tmp_runn_load_test_stuck_on_gh_actions/actions/runs/12704061252

<details>
  <summary>.github/workflows/test.yaml</summary>

```yaml
name: Test
on:
  push:
    branches:
      - main
  pull_request:
defaults:
  run:
    shell: bash
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  test_on_ubuntu_latest:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - uses: actions/checkout@v4
      - name: Install runn
        env:
          RUNN_VERSION: v0.122.3
        run: |
          RUNN_BIN_URL="https://github.com/k1LoW/runn/releases/download/${RUNN_VERSION}/runn_${RUNN_VERSION}_linux_amd64.tar.gz"
          curl -sL -o runn.tar.gz "$RUNN_BIN_URL"
          tar -xvf runn.tar.gz
          sudo mv runn /usr/local/bin/
      - run: |
          runn run hello_world.yaml --scopes run:exec
      - run: |
          runn loadt hello_world.yaml --scopes run:exec
  test_on_macos_latest:
    runs-on: macos-latest
    timeout-minutes: 1
    steps:
      - uses: actions/checkout@v4
      - name: Install runn
        run: |
          brew install k1LoW/tap/runn
          runn --version
      - run: |
          runn run hello_world.yaml --scopes run:exec
      - run: |
          runn loadt hello_world.yaml --scopes run:exec
```

</details>

<details>
  <summary>hello_world.yaml</summary>

```yaml
desc: Hello, World!
steps:
  - exec:
      command: echo "Hello, World!"
```

</details>

reproduced repo: https://github.com/mi-wada/tmp_runn_load_test_stuck_on_gh_actions/blob/main/.github/workflows/test.yaml

## Expected behavior

Finish after about 10 secs as a default `duration`.

## My investigation log

* The command `runn loadt hello_world.yaml --scopes run:exec` works well on my MacBook.
* Maybe these lines are the cause. I run only these lines on GitHub Actions, it also meets timeout. [exec log](https://github.com/mi-wada/tmp_runn_load_test_stuck_on_gh_actions/actions/runs/12704061261/job/35412830935)
  * https://github.com/k1LoW/runn/blob/1f373badcae6df4382daebfa447d9c44feba9082/cmd/loadt.go#L93-L101
