### ISSUE TITLE
Make captured responses persistent and available as expected values

### ISSUE THREAD

**Issue by k2tzumi** [k1LoW/runn#116]
# Motivation

We want to be able to use actual responses to ensure accurate validation.
While it is possible to prepare response data manually, scenario creation is more efficient when captured data can be used quickly.

# Ideas

* Added file output option to dump syntax.
* Make the response of each step of the Runn command output to a file as an option when the command is executed.

**Comment by k1LoW** [comment]
> Make the response of each step of the Runn command output to a file as an option when the command is executed.

Sounds like an idea like [`golden.Update()`](https://github.com/tenntenn/golden) !

I think it would be better if the output responses and query results could be used as input as directly as possible.

**Comment by k2tzumi** [comment]
This idea comes from the flow of creating a test using VCR

What is VCR?
https://github.com/vcr/vcr

There is also a golang implementation of VCR
https://github.com/dnaeon/go-vcr

A test using VCR will behave as follows

1. does it exist in a cassette that matches the request content?
2. if the request content matches, replay the response paired with the request

We wanted to reduce the cost of creating and maintaining test scenarios by using this flow as a reference

1. is there a cassette that matches the request content?
2. If it matches the request content, verify the expected value in the response paired with the request

VCR also has the ability to re-capture

**Comment by k2tzumi** [comment]
> [vcr.gem](https://github.com/vcr/vcr)

I am glad you have an image of a similar concept! 😄

**Comment by k2tzumi** [comment]
We believe that a deep dive into this proposal will lead to the following goals

* Reduce the burden of scenario creation and maintenance
* Support for Golden Test

**Comment by k1LoW** [comment]
> Make the response of each step of the Runn command output to a file as an option when the command is executed.

For another use case, I wanted to keep an execution log of all the inputs (requests) and outputs (responses) of each step in a runbook for routine operations.

**Comment by k1LoW** [comment]
With the introduction of `type Capturer interface`, it is now possible to capture the results of a runn run in any format.

This is at least sufficient for use with go test.

However, if you use runn as a CLI tool, you will not benefit from this interface.

Currently, I can only come up with a way to implement a built-in capture feature similar to debugger.

If possible, we would like to find a more flexible approach.

**Comment by k2tzumi** [comment]
https://github.com/k1LoW/runn/blob/main/capturer_test.go#L56-L64

It is wonderful that the golden test is done!

> However, if you use runn as a CLI tool, you will not benefit from this interface.
>
> Currently, I can only come up with a way to implement a built-in capture feature similar to debugger.
>
> If possible, we would like to find a more flexible approach.

I thought it would be better to implement it in the form of an optional parameter when executing the CLI.

```
runn run path/to/scenario.yml --capture path/to/save
```

It would be easier to use without adding syntax since there is no need to capture every time the scenario is executed.

I thought it was necessary to devise a way to split the capture files for each runner.

**Comment by k1LoW** [comment]
> I thought it would be better to implement it in the form of an optional parameter when executing the CLI.

Are you suggesting that we should implement Built-in capture?

For now, the two formats I'm thinking of for built-in capture are Runbook(YAML) and JSON.

**Comment by k2tzumi** [comment]
> Are you suggesting that we should implement Built-in capture?

Once we confirm that the current capture functionality works well, we hope to be able to incorporate it!
I thought about when to make it callable from the CLI, but thought it would be better to do it much later.

> For now, the two formats I'm thinking of for built-in capture are Runbook(YAML) and JSON.

I thought it was interesting that you could even output Runbook.
Does this mean that the Golden Test scenario will be output?
I think there is a Runbook for creating that scenario, but do you imagine that the Runbook itself will be optimized?

**Comment by k1LoW** [comment]
> Does this mean that the Golden Test scenario will be output?

My idea of the Runbook output image is as follows.

### Input runbook

```yaml
desc: Test using HTTP
vars:
  user_id: 1
runners:
  req: https://example.com
steps:
  postusers:
    desc: Post /users
    req:
      /users:
        post:
          body:
            application/json:
              username: alice
              password: passw0rd
  getusers:
    desc: Get /users/{{ vars.user_id }}
    req:
      /users/{{ vars.user_id }}:
        get:
          body:
            application/json:
              nil
```

### Captured runbook output

```yaml
      fmt.Println("\n------------------------------------------------------------------")
desc: http.yml
runners:
  req: "[THIS IS HTTP RUNNER]"
steps:
  -
    req:
      /users:
        post:
          body:
            application/json:
              username: alice
              password: passw0rd
    test: |
      current.res.status == 201
      && compare(current.res.headers, { [...] })
      && compare(current.res.body, { [...] })
  -
    req:
      /users/1:
        get:
          body:
            application/json:
              nil
    test: |
      current.res.status == 200
      && compare(current.res.headers, { [...] })
      && compare(current.res.body, { [...] })
```
