### ISSUE TITLE
Including string literal `{{ ... }}` in HTTP request body

### ISSUE THREAD

**Issue by kim-seungsu-edash** [k1LoW/runn#1185]
I'm sorry for create duplicated issue. I don't have a permission to re-opening original issue #828 .

As same as the original issue, i also want test API with request body which has `{{ ... }}` literal.
I'm trying to solution in [this comment](https://github.com/k1LoW/runn/issues/828#issuecomment-1986678467) like this:
```yaml
          body:
            application/json:
              reminder:
                subject: "\{\{COMPANY_NAME\}\} \{\{USER_NAME\}\}"
                body: "\{\{COMPANY_NAME\}\} \{\{USER_NAME\}\}"
```

but, the received request body was
```json
{
  "reminder": {
    "body": "\\{\\{COMPANY_NAME\\}\\} \\{\\{USER_NAME\\}\\}",
    "subject": "\\{\\{COMPANY_NAME\\}\\} \\{\\{USER_NAME\\}\\}"
  }
}
```

Please let me know if there is any other solution.
