### ISSUE TITLE
[Feature request] Add response comparison property to runnbooks

### ISSUE THREAD

**Issue by marimelon** [k1LoW/runn#1208]
I want to be able to directly compare API responses without defining redundant variables.

Currently, we have to define variables just for response comparison, which is verbose:

```yaml
vars:
  a_res: "json://./response/sample_a.json"

steps:
  - req:
      /sample:
        get:
          body:
            application/json: null
    test: |
      current.res.status == 200 && compare(current.res.body, vars.a_res)
```

Instead, I'd like to directly reference expected response files in steps:

```yaml
steps:
  - req:
      /sample:
        get:
          body:
            application/json: null
    test: |
      current.res.status == 200
    testRes: "json://./response/sample_a.json"
```

---

Additionally, it would be helpful to have a CLI option to dump these expected responses. For example:

```
runn run --dump-res path/to/runnbook.yml
```

This would generate response files for each step with a `testRes` property, making it easy to create initial response templates or update existing ones based on actual responses.

**Comment by k1LoW** [comment]
@marimelon Thank you for your request!

It seems very convenient. However, there needs to be a stronger reason to create a section that only treats HTTP Runner specially in runn.

It is easier to accept if it is a more general-purpose interface.

Thank you!

**Comment by marimelon** [comment]
Thank you for your feedback!

It is certainly important to maintain a generic interface. By allowing variable definition within each step, I can partially achieve my goal of reducing verbosity and enhancing readability. This approach would still offer flexibility across different contexts, not just for HTTP Runner.

For example, the runbook could look like:

```yaml
steps:
  - req:
      /sample:
        get:
          body:
            application/json: null
    vars:
      expected_res: "json://response/sample_a.json"
    test: |
      current.res.status == 200 && compare(current.res.body, expected_res)
```

**Comment by k1LoW** [comment]
I like the idea of `step[*]vars:` ( `step.<key>.vars:`) .

> I can partially achieve my goal.

Is it better if there is a function that can read files in the built-in function?

For example,

```yaml
steps:
  - req:
      /sample:
        get:
          body:
            application/json: null
    test: |
      current.res.status == 200 && compare(current.res.body, file('json://response/sample_a.json'))
```
