### ISSUE TITLE
Support for get data in test

### ISSUE THREAD

**Issue by dungtqbap** [k1LoW/runn#1221]
When i using code 
```
test: |
      // ステータスコードが200であること
      current.res.status == 200
      // 編集した値が返ってくること
      && current.res.body.fileName == "abc.pdf"
      && current.res.body.fileId == "{{ steps.A.res.body.fileId }}"
```
Then the error occurs that the actual value of steps in the test cannot be obtained.
```
current.res.body.fileId == "{{ steps.A.res.body.fileId }}" => false
        ├── current.res.body.fileId => "01963df2-08b7-7d5c-963a-bfcef42688e9"
        └── "{{ steps.A.res.body.fileId }}"
```
Because fileId is dynamic data, it cannot be set hard.
Could you please help support this?

**Comment by k1LoW** [comment]
Delimiters are not required for test runner statements 👍 

```
current.res.body.fileId == steps.A.res.body.fileId
```

**Comment by k1LoW** [comment]
I recommend [the online books](https://github.com/k1LoW/runn?tab=readme-ov-file#online-book).

In particular, [the tutorial](https://zenn.dev/katzumi/books/runn-tutorial) is an easy way to understand the world of runn 👍

**Comment by dungtqbap** [comment]
I tried again with your output and removed the space.
But the error still occurs as before

**Comment by k1LoW** [comment]
How did you write it?

An example of a minimalist run book that actually works would make it easier to solve the problem.

**Comment by dungtqbap** [comment]
This is example : 
```
  NormalTestAttachAgreedContract:
    desc: 正常系-編集可能なフィールドの値を全て更新
    req:
      url:
        post:
          headers:
          body:
            application/json:
    test: |
      current.res.status == 200
      && compare(current.res.body, vars.response, ["updateTime", "createTime", "attachedLocfileVersionId", "locfileId", "locfileVersionId"])
  AfterNormalTestAttach:
    desc: 正常系の反映確認
    req:
      url:
        post:
          headers:
          body:
            application/json:
    test: |
      // ステータスコードが200であること
      current.res.status == 200
      // 編集した値が返ってくること
      && current.res.body.versionSummaryList[1].fileName == "編集前_Attach_Version_Agreed_Contract.pdf"
      && current.res.body.versionSummaryList[1].locfileVersionId == "{{steps.NormalTestAttachAgreedContract.res.body.attachedLocfileVersionId}}"

```
My question is how can I get data for the test part in the section:
      && current.res.body.versionSummaryList[1].locfileVersionId == "{{steps.NormalTestAttachAgreedContract.res.body.attachedLocfileVersionId}}"

My errors :
current.res.body.versionSummaryList[1].locfileVersionId == "{{steps.NormalTestAttachAgreedContract.res.body.attachedLocfileVersionId}}" => false
        ├── current.res.body.versionSummaryList[1].locfileVersionId => "01963e0e-7857-7304-a761-8d6738f0fb22"
        └── "{{steps.NormalTestAttachAgreedContract.res.body.attachedLocfileVersionId}}"
