### ISSUE TITLE
Improved vars takeover when using multi-level includes

### ISSUE THREAD

**Issue by k2tzumi** [k1LoW/runn#139]
# Problem

Inability to successfully take over vars when included at multiple levels

* a.yml
```yaml
vars:
   foo: 123
steps:
  -
   include: b.yml
   vars:
     foo: '{{ vars.foo }}'

.. snip ..
```
* b.yml
```yaml
vars:
   foo: 123
steps:
  -
   include: c.yml
   vars:
     foo: '{{ vars.foo }}'

.. snip ..
```
* c.yml
```yaml
vars:
   foo: 123
steps:
  -
    test: vars.foo == 123
```

Error when executing a.yml
The value of foo is the string `'123'`.

# Question

If I want to specify overwriting the vars in `c.yml` from `a.yml` in the above example, is the above description the only way?
Is there any problem to make the specification that vars defined in the parent yaml are inherited?
When specifying vars at include time, I feel that numerical values are inevitably evaluated as strings.

**Comment by k1LoW** [comment]
> If I want to specify overwriting the vars in c.yml from a.yml in the above example, is the above description the only way?

Yes.

> When specifying vars at include time, I feel that numerical values are inevitably evaluated as strings.

You are exactly right.
Currently only [bool values are converted to heuristic](https://github.com/k1LoW/runn/blob/2b3027b924b0dc0b9e6965d96541071793125f26/eval.go#L15-L23), which is a known issue with Include Runner.

**Comment by k2tzumi** [comment]
Thanks.

> Currently only [bool values are converted to heuristic](https://github.com/k1LoW/runn/blob/2b3027b924b0dc0b9e6965d96541071793125f26/eval.go#L15-L23), which is a known issue with Include Runner.

I wish I had a better approach to a solution to this problem, but I will read the source and think about it.

I would like to know if there are any best practices for writing scenarios with a large number of steps efficiently, do you know of any good ones?
If each scenario itself is an executable and reusable description, it tends to include many steps.

Would it be preferable to create an include-only scenario file with limited nesting?
In such cases, however, it is necessary to move the include-only scenario file to a different directory or otherwise remove it from the execution target.

**Comment by k2tzumi** [comment]
> Is there any problem to make the specification that vars defined in the parent yaml are inherited?

The image is that vars are cascaded and taken over as vars at include time.

```yml
vars:
   foo: 123
steps:
  -
   include: b.yml
   vars:
# Make vars inherit without having to redefine them.
# Include with the value of the original int
#     foo: '{{ vars.foo }}'

.. snip ..
```

I figured this way the expression would not be internally re-evaluated and the original type would be maintained.
