### ISSUE TITLE
Add option not to check redirect in CLI

### ISSUE THREAD

**Issue by takumakume** [k1LoW/runn#197]
[go net/http client](https://pkg.go.dev/net/http#Client.CheckRedirect) performs redirect by default.
I had a problem when I wanted to test before redirect.

When using runn as a golang helper, I would use [HTTPRunnerWithHandler](https://github.com/k1LoW/runn/blob/1d6d871e504b48ab2662d49a0723ebfb835eac02/option.go#L250). But it can't be change from the CLI.

For example, in the case of the `curl -L ..` can be used to redirect. (default is no redirect).

I suggest adding a runner option as follows:

```yaml
# Example
runners:
  req:
    endpoint: ...
    openapi3: ...
    skip_check_redirect: true
```
