### ISSUE TITLE
Support Basic auth

### ISSUE THREAD

**Issue by atsushi-ishibashi** [k1LoW/runn#286]
If build-in function `base64encode` is prepared, we can write like below?
```
vars:
  user: "hoge"
  password: "fuga"
steps:
  auth:
    req:
      /hoge:
       post:
          headers:
            Authorization: "Basic {{ base64encode({{ vars.user }}:{{ vars.password }}) }}"
```
