### ISSUE TITLE
Can we step response in later step

### ISSUE THREAD

**Issue by atsushi-ishibashi** [k1LoW/runn#287]
What I want to do is
```
vars:
  itemId: ${TEST_ITEM_ID}
steps:
  hoge:
    req:
      /api1:
       get:
    test: |
      ## sorry like go
      for _, v := range hoge.res.body.items {
        if v.id == {{ vars.itemId }} {
          set_var("itemName", v.name)
        }
      }
  fuga:
    req:
      /items/{{ vars.itemName }}:
        get:
```

Can I do the case by current features?

**Comment by k1LoW** [comment]
How about the following? (you can run it as is.)

```yaml
vars:
  itemId: B
  items:
    - itemId: A
      name: Product A
    - itemId: B
      name: Product B
    - itemId: C
      name: Product C
steps:
  hoge:
    bind:
      itemName: filter(vars.items, {.itemId == vars.itemId})[0].name
  fuga:
    dump: itemName
```
