### ISSUE TITLE
[Question] Is there a skip and only functionality for step execution?

### ISSUE THREAD

**Issue by yuya-okada527** [k1LoW/runn#378]
Thanks for great tool!

Is there a skip or only functionality for step execution?  I found skipTest option, but it is skipping only test section, right?  I want an option to skip entire steps or execute certain steps, because such functionality helps us to focus on a small subset of test cases and speed up writing tests.

I'm imaging something like this(https://playwright.dev/docs/test-annotations#focus-a-test).

I apologize, if I missed something.

**Comment by k2tzumi** [comment]
Hi @yuya-okada527 

It is possible to skip a step by using an `if` section. 
https://github.com/k1LoW/runn#if

However, I don't have the ability to temporarily skip the entire runbook.
Currently, the way to manage the test suite is to separate the runbook directory, categorize the scenarios you want to run, and then narrow down the tests.

For example, you can specify a directory and run it as follows.
```console
$ runn run testsuite-a/**/*.yml
```

**Comment by k2tzumi** [comment]
> However, I don't have the ability to temporarily skip the entire runbook.

Sorry. I was able to skip the entire runbook by using the if section at the top level.

**Comment by k2tzumi** [comment]
How about the following?

* test-a.yml
  ```yaml
  desc: Test suite A
  if: ${TEST_SUITE_A:-false}
  steps:
    -
      exec:
        command: echo "Testing test suite A"
    -
      dump: previous.stdout
  ```
* test-b.yml
  ```
  desc: Test suite B
  if: ${TEST_SUITE_B:-false}
  steps:
    -
      exec:
        command: echo "Testing test suite B"
    -
      dump: previous.stdout
  ```

* Execution example(To run Test suite A)
  ```console
  $ TEST_SUITE_A=true runn run *.yml     
  Testing test suite A
  
  Test suite A ... ok
  Test suite B ... skip
  
  2 scenarios, 0 skipped, 0 failures
  ```

* Execution example(To run Test suite B)
  ```console
  $ TEST_SUITE_B=true runn run *.yml
  Test suite A ... skip
  Testing test suite B
  
  Test suite B ... ok
  
  2 scenarios, 0 skipped, 0 failures
  ```
