### ISSUE TITLE
Fail section

### ISSUE THREAD

**Issue by k2tzumi** [k1LoW/runn#397]
# What is this?

Fail section that always fails when described.

# Use Cases

This is when you want to make a scenario fail after some operation in a later step when you already know that the previous step failed.

A more concrete example would be an API call that results in a 500 error and you want to display the application log.

* example
  ```yml
  steps:
    -
      req:
        desc: Some kind of error occurs. Errors are not evaluated here.
        /fail-end-point:
          get:
            body: null
    -
      desc: Handling errors
      if: previous.res.status == 500
      exec:
        command: tail -10 /var/log/error.log
      # Whenever there is a FAIL section, it fails and does not evaluate the subsequent steps.
      fail: 'Fail messages.'
  ```

**Comment by k2tzumi** [comment]
I can do the following, but I would like to display the appropriate message

```yml
steps:
  -
    req:
      desc: Some kind of error occurs. Errors are not evaluated here.
      /fail-end-point:
        get:
          body: null
  -
    desc: Handling errors
    if: previous.res.status == 500
    exec:
      command: tail -10 /var/log/error.log
    test: false
```
