### ISSUE TITLE
Allow out attribute of dump section to be specified by variable

### ISSUE THREAD

**Issue by k2tzumi** [k1LoW/runn#398]
For example, the following statement

```yml
vars:
   path: "path/to"
step:
   dump:
     expr: "dump"
     out: {{ vars.path }}
```

If this is already possible, I may be mistaken.
