### ISSUE TITLE
Cannot test if elements are contained in array when mapping object array responded from an external web server

### ISSUE THREAD

**Issue by IzumiSy** [k1LoW/runn#409]
# Preparation
test.yaml
```yaml
desc: object array mapping
vars:
  expected: [10, 20]
runners:
  req: http://localhost:8000
steps:
  a:
    req:
      /resp.json:
        get:
          body: null
  b:
    test: vars.expected in map(steps.a.res.body, {#.value})
```
resp.json
```json
[
  { "value": 10 },
  { "value": 20 },
  { "value": 30 }
]
```
run a mock server responding with the resp.json
```bash
$ python3 -m http.server
```

# Result
```bash
$ runn run test.yaml --debug
Run 'req' on 'object array mapping'.steps.a
-----START HTTP REQUEST-----
GET /resp.json HTTP/1.1
Host: localhost:8000


-----END HTTP REQUEST-----
-----START HTTP RESPONSE-----
HTTP/1.0 200 OK
Connection: close
Content-Length: 60
Content-Type: application/json
Date: Thu, 09 Feb 2023 00:41:33 GMT
Last-Modified: Wed, 08 Feb 2023 08:14:49 GMT
Server: SimpleHTTP/0.6 Python/3.10.8

[
  { "value": 10 },
  { "value": 20 },
  { "value": 30 }
]

-----END HTTP RESPONSE-----

Run 'test' on 'object array mapping'.steps.b
object array mapping ... failed to run test.yaml: test failed on 'object array mapping'.steps.b: (vars.expected in map(steps.a.res.body, {#.value})) is not true
vars.expected in map(steps.a.res.body, {#.value})
├── vars.expected => [10,20]
├── map(steps.a.res.body, ) => ?
├── steps.a.res.body => [{"value":10},{"value":20},{"value":30}]
└──  => ?


1 scenario, 0 skipped, 1 failure
```

**Expected**: it should succeed, but looks like a compiler cannot understand types when using map function.

I don't understand why mapping says `map(steps.a.res.body, ) => ?`. It just can extract values by keys from an object array.

The another thing I have observed is that it works as expected when I don't use response coming from web servers but put the same response in `vars` instead. I don't know why but it looks typed.

**Comment by k1LoW** [comment]
@IzumiSy Thank you for your report!

**Comment by k1LoW** [comment]
By the way, does the test pass if follows?

```yaml
desc: object array mapping
vars:
  expected: [10, 20]
runners:
  req: http://localhost:8000
steps:
  a:
    req:
      /resp.json:
        get:
          body: null
  b:
    test: vars.expected[0] in map(steps.a.res.body, {#.value})
  c:
    test: vars.expected[1] in map(steps.a.res.body, {#.value})
```

ref: https://expr.medv.io/docs/Language-Definition#membership-operator
