### ISSUE TITLE
Cannot refer a binded value when using map function

### ISSUE THREAD

**Issue by IzumiSy** [k1LoW/runn#410]
## Reproduction
test.yaml
```yaml
desc: object map binding
vars:
  value: [
    { "value": 10 },
    { "value": 20 },
    { "value": 30 }
  ]
steps:
  a:
    bind:
      extracted: map(vars.value, {#.value})
  b:
    test: len(steps.a.extracted) == 3
```

Result
```bash
$ runn run test.yaml --debug
Run 'bind' on 'object map binding'.steps.a

Run 'test' on 'object map binding'.steps.b
object map binding ... failed to run test.yaml: test failed on 'object map binding'.steps.b: eval error: invalid argument for len (type <nil>) (1:1)
 | len(steps.a.extracted) == 3
 | ^

1 scenario, 0 skipped, 1 failure
```

**Expected:** It should succeed (or my syntax is wrong?)

**Comment by IzumiSy** [comment]
This is working though
```yaml
desc: object map binding
vars:
  value: [
    { "value": 10 },
    { "value": 20 },
    { "value": 30 }
  ]
steps:
  b:
    test: len(map(vars.value, {#.value})) == 3
```

**Comment by k1LoW** [comment]
If you set the value with `bind:`, it will be set to the top level of the store.

```yaml
desc: object map binding
vars:
  value: [
    { "value": 10 },
    { "value": 20 },
    { "value": 30 }
  ]
steps:
  a:
    bind:
      extracted: map(vars.value, {#.value})
  b:
    test: len(extracted) == 3
```

```console
$ runn run tmp.yml
object map binding ... ok

1 scenario, 0 skipped, 0 failures
```
