### ISSUE TITLE
Type inference does not work with diff and intersect

### ISSUE THREAD

**Issue by IzumiSy** [k1LoW/runn#415]
# Reproduction
test.yaml
```
desc: intersect diff
vars:
  v1: [1, 2, 3, 4]
  v2: [2, 3]
  v3: [2, 3]
steps:
  a:
    test: diff(intersect(vars.v1, vars.v2), vars.v3) == false
```
Result
```bash
$ runn run intersect_diff.yaml
intersect diff ... failed to run intersect_diff.yaml: test failed on 'intersect diff'.steps.a: (diff(intersect(vars.v1, vars.v2), vars.v3) == false) is not true
diff(intersect(vars.v1, vars.v2), vars.v3) == false
├── diff(, vars.v3) => ?
├──  => ?
├── vars.v3 => [2,3]
└── false => false


1 scenario, 0 skipped, 1 failure
```

**Expection**: it should succeed, but looks like the compiler cannot understand the type returned by `intersect` function.

**Comment by k1LoW** [comment]
`diff()` returns `string`

```
desc: intersect diff
vars:
  v1: [1, 2, 3, 4]
  v2: [2, 3]
  v3: [2, 3]
steps:
  z:
    dump: intersect(vars.v1, vars.v2)
  zz:
    dump: diff(intersect(vars.v1, vars.v2), vars.v3)
  a:
    test: diff(intersect(vars.v1, vars.v2), vars.v3) == ""
```

**Comment by IzumiSy** [comment]
wow, thanks! 🙏

**Comment by IzumiSy** [comment]
I found the situation that does not work as expected.

test.yaml
```yaml
desc: intesect diff
vars:
  v1: [2, 3]
  v2: [1, 2, 3, 4]
steps:
  a:
    test: diff(intersect(vars.v1, vars.v2), v1) == ""
```
Result
```bash
$ runn run intersect-diff.yaml
intesect diff ... failed to run intersect-diff.yaml: test failed on 'intesect diff'.steps.a: (diff(intersect(vars.v1, vars.v2), v1) == "") is not true
diff(intersect(vars.v1, vars.v2), v1) == ""
├── diff(, v1) => ?
├──  => ?
├── v1 => null
└── "" => ""


1 scenario, 0 skipped, 1 failure
```
What I would like to achieve is checking all elements in `vars.v1` is contained in `vars.v2`.

Any idea to achieve this without getting errors?

**Comment by IzumiSy** [comment]
@k1LoW 
I found the situation that does not work as expected.

test.yaml
```yaml
desc: intesect diff
vars:
  v1: [2, 3]
  v2: [1, 2, 3, 4]
steps:
  a:
    test: diff(intersect(vars.v1, vars.v2), v1) == ""
```
Result
```bash
$ runn run intersect-diff.yaml
intesect diff ... failed to run intersect-diff.yaml: test failed on 'intesect diff'.steps.a: (diff(intersect(vars.v1, vars.v2), v1) == "") is not true
diff(intersect(vars.v1, vars.v2), v1) == ""
├── diff(, v1) => ?
├──  => ?
├── v1 => null
└── "" => ""


1 scenario, 0 skipped, 1 failure
```
What I would like to achieve is checking all elements in `vars.v1` is contained in `vars.v2`.

Any idea to achieve this without getting errors?

**Comment by k1LoW** [comment]
Incorrect variable specified.

test: diff(intersect(vars.v1, vars.v2), **v1**) == ""

Use `vars.v1` instead of `v1`.

```yaml
desc: intesect diff
vars:
  v1: [2, 3]
  v2: [1, 2, 3, 4]
steps:
  a:
    test: diff(intersect(vars.v1, vars.v2), vars.v1) == ""
```

**Comment by IzumiSy** [comment]
I see. Thanks!

**Comment by IzumiSy** [comment]
@k1LoW 
Sorry for too many times to ping you, but this would be the last one 🙏 

Do you find any sintax error in my test?

test.yaml
```yaml
desc: intersect diff
runners:
  req: http://localhost:8000
steps:
  v1:
    include:
      path: ./resp1.yaml
    dump: steps.v1.result
  v2:
    include:
      path: ./resp2.yaml
    dump: steps.v2.result
  a:
    test: diff(intersect(steps.v1.result, steps.v2.result), steps.v1.result) == ""
```
resp1.yaml
```yaml
desc: resp1
runners:
  req: http://localhost:800
steps:
  v1:
    req:
      /resp1.json:
        get:
          body: null
    bind:
      result: map(current.res.body, {#.value})
```
resp2.yaml
```yaml
desc: resp2
runners:
  req: http://localhost:8000
steps:
  v1:
    req:
      /resp2.json:
        get:
          body: null
    bind:
      result: map(current.res.body, {#.value})
```
resp1.json
```json
[
  { "value": 1 },
  { "value": 2 },
  { "value": 3 },
  { "value": 4 }
]
```
resp2.json
```json
[
  { "value": 2 },
  { "value": 3 }
]
```
Result
```bash
$ runn run test.yaml --debug
Run 'include' on 'intersect diff'.steps.v1
Run 'req' on 'resp1'.steps.v1
-----START HTTP REQUEST-----
GET /resp1.json HTTP/1.1
Host: localhost:8000


-----END HTTP REQUEST-----
-----START HTTP RESPONSE-----
HTTP/1.0 200 OK
Connection: close
Content-Length: 75
Content-Type: application/json
Date: Fri, 10 Feb 2023 04:26:02 GMT
Last-Modified: Fri, 10 Feb 2023 04:21:24 GMT
Server: SimpleHTTP/0.6 Python/3.10.8

[
  { "value": 1 },
  { "value": 2 },
  { "value": 3 },
  { "value": 4 }
]

-----END HTTP RESPONSE-----
Run 'bind' on 'resp1'.steps.v1
Run 'dump' on 'intersect diff'.steps.v1
[
  1,
  2,
  3,
  4
]

Run 'include' on 'intersect diff'.steps.v2
Run 'req' on 'resp2'.steps.v1
-----START HTTP REQUEST-----
GET /resp2.json HTTP/1.1
Host: localhost:8000


-----END HTTP REQUEST-----
-----START HTTP RESPONSE-----
HTTP/1.0 200 OK
Connection: close
Content-Length: 39
Content-Type: application/json
Date: Fri, 10 Feb 2023 04:26:02 GMT
Last-Modified: Fri, 10 Feb 2023 04:21:42 GMT
Server: SimpleHTTP/0.6 Python/3.10.8

[
  { "value": 2 },
  { "value": 3 }
]

-----END HTTP RESPONSE-----
Run 'bind' on 'resp2'.steps.v1
Run 'dump' on 'intersect diff'.steps.v2
[
  2,
  3
]

Run 'test' on 'intersect diff'.steps.a
intersect diff ... failed to run test.yaml: test failed on 'intersect diff'.steps.a: (diff(intersect(steps.v1.result, steps.v2.result), steps.v1.result) == "") is not true
diff(intersect(steps.v1.result, steps.v2.result), steps.v1.result) == ""
├── diff(, steps.v1.result) => ?
├──  => ?
├── steps.v1.result => [1,2,3,4]
└── "" => ""


1 scenario, 0 skipped, 1 failure
```
