### ISSUE TITLE
Set the endpoint of runners

### ISSUE THREAD

**Issue by beexli** [k1LoW/runn#442]
I want to send a request to the url obtained in the previous step, but runners do not allow setting variables and the following error is reported.

> failed to run /books/jobs/xxx/xxx.yml: http request failed on 'xxxxxxxxx'.steps.xxxxxxxxxx: Get "%7B%7B%20previous.res.body.xxxxxxxx%5B0%5D%20%7D%7D": unsupported protocol scheme ""

The runners are set as follows.
```
desc: xxxxxxxx
if: included
runners:
  myapi:
    endpoint: "{{ previous.res.body.xxxxxx[0] }}"
steps:
  xxxxxxxx:
    myapi:
      /:
        get:
          headers:
            Cookie: xxxxxxxxx
    test: |
      vars.skip_test == true || current.res.status == 200
```

What should I do if I want to use the url obtained from the previous step?
