### ISSUE TITLE
Proposal: GraphQL runner

### ISSUE THREAD

**Issue by IzumiSy** [k1LoW/runn#514]
This is the proposal issue on supporting GraphQL runner (like gRPC runner)

I know the current implementation already supports GraphQL request, but I have an idea to improve the usability.

# Example

```yaml
runners:
  gqlreq: https://gql.example.com/query
steps:
  - desc: GraphQL request
    gqlreq:
       headers:
         authorization: bearer xxxxxx
       query: |
         mutation createUser(
           $name: String!, 
           $age: Int!,
           $enabled: Bool
         ) {
           createUser(name: $name, age: $age, enabled: $enabled) {
             id
           }
         }
       variables:
         name: alice
         age: 30
         enabled: true
```

# Advantage

### Simpler request definition
In GraphQL with HTTP request, requesting URL (`/query`), method (`POST`), Content-Type (`application/json`), requesting body (`query` key) are almost always constant. 

Currently, in the case using HTTP request form , we have to have several nesting keys like as follows:

```yaml
steps:
  - desc: GraphQL request
    req:
      /query
        post:
          headers:
            authorization: "bearer xxxxxx"
          body:
            application/json:
              query: |
                mutation {
                  createUser(
                    name: "alice", 
                    age: 30, 
                    enabled: true
                  ) {
                    id
                  }
                }
```

Constant keys (`req."/query".post.body."application/json".query"`) are redundunt. 

I think they can be omitted if GraphQL runner is supported.

### Null variable support

Currently, we have no way to set `null` on GraphQL request.

```yaml
vars:
  enabled: null
steps:
  - desc: GraphQL request
    req:
      /query
        post:
          headers:
            authorization: "bearer xxxxxx"
          body:
            application/json:
              query: |
                mutation {
                  createUser(
                    name: "alice", 
                    age: 30, 

                    # Oops... this will just be empty, but here should be "enabled: null"
                    # "{{ vars.enabled }}" will be stringified null (eg. "null")
                    enabled: {{ vars.enabled }} 
                  ) {
                    id
                  }
                }
```

So I would like to support `variable` at the same level of `headers` and `query` which does not omit `null` as an empty value.

```yaml
steps:
  - desc: GraphQL request
    gqlreq:
       headers:
         authorization: bearer xxxxxx
       query: |
         mutation createUser(
           $name: String!, 
           $age: Int!,
           $enabled: Bool
         ) {
           createUser(name: $name, age: $age, enabled: $enabled) {
             id
           }
         }
       variables:
         name: alice
         age: 30
         enabled: null # this will send `null` in `enabled` key.
```

If this proposal sounds good to you, let me work on implementation on GraphQL runner.

Supporting GraphQL runner will make better experience for GraphQL users (like me!)

Any thought? @k1LoW

**Comment by k1LoW** [comment]
@IzumiSy I think it is a very great idea!
If you could implement it, I couldn't be happier!

**Comment by IzumiSy** [comment]
I am closing this proposal.

What I would like to achieve in this proposal is the thing I have overlooked. 

Using `variables` with `query` in body is legit enough for me to pass `null` values in requests.

```yaml
desc: cg
vars:
  name: testGroup
  code: null
runners:
  req: ${RUNNER_HOST:-http://localhost:8000}/query
steps:
  login:
    include:
      path: steps/login.yaml

  createGroup:
    req:
      /:
        post:
          headers:
            authorization: "bearer {{ steps.login.token }}"
          body:
            application/json:
              query: |
                mutation(
                  $name: String!
                  $code: String
                ) {
                  createGroup(input: {
                    name: $name,
                    code: $code
                  }) {
                    id
                  }
                }
              variables:
                name: "{{ vars.name }}"
                code: "{{ vars.code }}" # here can pass `null` that I have wanted to.
```

Thanks for accepting my proposal, but maybe another time.
