### ISSUE TITLE
How to req in ssh conneted server

### ISSUE THREAD

**Issue by t-kitamura-axel** [k1LoW/runn#526]
I try to api test in ssh server like bellow  yaml. 
But, not working. 
Doesn't `runn` support  api test in ssh server?
Or, do I have misswriting  yaml?

- yaml
```
desc: api test in ssh server
runners:
  sc:
    host:  jump
    keepSession: true
  req:
    endpoint: https:/xxx/xxxxx
steps:
  jump_ls:
    sc:
      req 
        xxxxx:
          get:
            headers:
              Content-Type: application/json
              Host: xxxx
              X-API-KEY: xxxxx
      test: steps.xxxx.res.status == 200

```

- command
```
docker run -it \
  --rm \
  --mount type=bind,src=/home/$USER/.ssh,dst=/root/.ssh \
  --add-host=host.docker.internal:host-gateway \
  --name runn \
  -v $PWD:/test \
  ghcr.io/k1low/runn:v0.52.3-slim \
  run test/api-test.yaml
```

- err message(selected)
```
 invalid path: req
```

**Comment by k1LoW** [comment]
>  invalid path: req

![CleanShot 2023-06-07 at 14 50 18](https://github.com/k1LoW/runn/assets/57114/f0a8c626-aff2-430a-ba9f-00b7d659bc58)

First, the red box looks incorrect as YAML syntax.

Also, `sc` is an SSH Runner and does not need to be specified for HTTP Requests.

I can't be sure because it is hidden by an `xxx`, but it seems to work correctly with the following modification.

```yaml
desc: api test in ssh server
runners:
  sc:
    host:  jump
    keepSession: true
  req:
    endpoint: https:/xxx/xxxxx
steps:
  jump_ls:
    req:
      xxxxx:
        get:
          headers:
            Content-Type: application/json
            Host: xxxx
            X-API-KEY: xxxxx
     test: steps.xxxx.res.status == 200
```

See also (Japanese / Paid content): https://zenn.dev/k1low/books/runn-cookbook/viewer/ssh-port-forwarding

**Comment by t-kitamura-axel** [comment]
Thank you for advice.
But I have error. `Client.Timeout exceeded while awaiting headers`
Detail bellow, Is this  not `runn`'s yaml setting  but my api and header miss in docker container?
I reffer to [this link](https://zenn.dev/kaityo256/scraps/c335ac8c76c5e1)

- err message
```
Run 'req' on 'xxxxx'.steps.xxxx_example
-----START HTTP REQUEST-----
GET /xxx/xxx/xxx/xx/xxxx/example HTTP/1.1
Host: vpce-xxxx.xxxx-api.xxx.vpce.amazonaws.com
Accept: application/json
Content-Type: application/json
X-Api-Key: xxxxxxxxxxx


-----END HTTP REQUEST-----
xxx xxx xxxx ... failed to run test/api-test.yaml: http request failed on 'xxxx'.steps.xxxx_example: Get "https://xxxxx.xxx-api.xxxx.vpce.amazonaws.com/xxx/xxx/xxx/xx/xxxxx/example": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
```

- yaml
```
runners:
  sc:
    host:  xxxxx
    keepSession: true
  req:
    endpoint: https://vpce-xxxx.xxx-api.xxx.vpce.amazonaws.com/xxx
debug: true
steps:
  xxx_example:
    req:
      /xxx/xxx/xx/xxx_xxx/example:
        get:
          headers:
            accept: application/json
            Content-Type: application/json
            Host: xxx.xxx-api.xxxx.amazonaws.com
            X-API-KEY: xxxxx
    test: steps.xxx_xxx_xxxx.res.status == 200

```

**Comment by t-kitamura-axel** [comment]
As a side note, ssh runnner's `curl command` is success.

 - yaml

```
runners:
  sc:
    host:  xxxxx
    keepSession: true
  req:
    endpoint: https://vpce-xxxx.xxx-api.xxx.vpce.amazonaws.com/xxx
debug: true:
steps:
  jump_create_status:
    sc:
      command: |-
        curl -iX 'GET' \
        '{{ vars.endpoint }}/xxx/xxx/xx/xxx_xxx/xxx' \
        -H 'Content-Type: {{ vars.header.content_type }}' \
        -H 'Host:{{ vars.header.host }}' \
        -H 'X-API-KEY: {{ vars.header.x_api_key }}'
    test:
        current.stdout contains '200 OK'
        && current.stdout contains 'xx xxx xxx xxx'

```

**Comment by k1LoW** [comment]
https://github.com/k1LoW/runn/issues/526#issuecomment-1579998357 and https://github.com/k1LoW/runn/issues/526#issuecomment-1580139258 have different HTTP Request routes.

- https://github.com/k1LoW/runn/issues/526#issuecomment-1579998357 is making an HTTP request from the host server.
- https://github.com/k1LoW/runn/issues/526#issuecomment-1580139258 is making an HTTP request from within the remote server.

**Comment by k1LoW** [comment]
> In spite of same endpoint and same path, only https://github.com/k1LoW/runn/issues/526#issuecomment-1579998357 is no successful.

> https://github.com/k1LoW/runn/issues/526#issuecomment-1579998357 and https://github.com/k1LoW/runn/issues/526#issuecomment-1580139258 have different HTTP Request routes.

This means that the network paths of the two HTTP requests are different.

**Comment by k1LoW** [comment]
Perhaps what you want to do can be achieved in the following ways

```yaml
runners:
  sc:
    host:  xxxxx
    keepSession: true
    localForward: '10443:vpce-xxxx.xxx-api.xxx.vpce.amazonaws.com:443'
  req:
    endpoint: https://127.0.0.1:10443/xxx
debug: true
steps:
  xxx_example:
    req:
      /xxx/xxx/xx/xxx_xxx/example:
        get:
          headers:
            accept: application/json
            Content-Type: application/json
            Host: xxx.xxx-api.xxxx.amazonaws.com
            X-API-KEY: xxxxx
    test: steps.xxx_xxx_xxxx.res.status == 200
```
