### ISSUE TITLE
In loop, json is recognized as string

### ISSUE THREAD

**Issue by t-kitamura-axel** [k1LoW/runn#534]
When I try to test bellow runn contents,  in roop, json is recognized as string

- runn contents
```
desc: xxxx xxxxx xxxx
vars:
  xxxxx_req:
    - "json://../../json/req/200/normal1.json"
    - "json://../../json/req/200/normal2.json"
  xxxxx_res:
    - "do some magic"
    - "do some magic"
steps:
  normal:
    desc:  xxxx xxxx xxxx xxxx
    loop:
      count: len(vars.xxxxx_req)
    req:
      /xxx/xxx/xx/xxxxx:
        post:
          headers:
            accept: "{{ vars.header.accept }}"
            Content-Type: "{{ vars.header.content_type }}"
            Host: "{{ vars.header.host }}"
            X-API-KEY: "{{ vars.header.x_api_key }}"
          body:
            application/json: "{{ vars.xxxxx_req[i] }}"
    test: steps.normal.res.status == 200
      && steps.normal.res.body contains vars.xxxxx_res[i]
```

- log 

```
-----START HTTP REQUEST-----
POST xxx/xx/xxx/xx HTTP/1.1
Host: xxxxx
Accept: application/json
Content-Type: application/json
X-Api-Key: xxxxxxx

"json://../../json/req/200/normal2.json" <- not json but string  

-----END HTTP REQUEST-----
```

In no roop, json is recognized correctly.

- runn contents

```
desc: xxx xxxx xxxx
vars:
  xxx_req: "json://../../json/req/200/normal1.json"
 steps:
  normal:
    desc:  xxx xxx xxx
    req:
      /xxx/xxx/xxx/xx:
        post:
          headers:
            accept: "{{ vars.header.accept }}"
            Content-Type: "{{ vars.header.content_type }}"
            Host: "{{ vars.header.host }}"
            X-API-KEY: "{{ vars.header.x_api_key }}"
          body:
            application/json: "{{ vars.xxx_req }}"
    test: steps.normal.res.status == 200
      && steps.normal.res.body contains "do some magic"
```

- log

```
-----START HTTP REQUEST-----
POST xxx/xxx/xxx/xx HTTP/1.1
Host: xxxx
Accept: application/json
Content-Type: application/json
X-Api-Key: xxxxxx

{"session": ${ normal1.json contents } <- json is json
-----END HTTP REQUEST-----

```

**Comment by k1LoW** [comment]
The `json://` and `yaml://` schemes are only allowed in the root of the `vars:` section.

**Comment by k1LoW** [comment]
I think it will be recognized as JSON if set as follows

https://github.com/k1LoW/runn/blob/f1038665a50f256571cb09d0346b0e8000d339d5/testdata/book/httpbin.yml#L22-L25

https://github.com/k1LoW/runn/blob/f1038665a50f256571cb09d0346b0e8000d339d5/testdata/book/httpbin.yml#L107

**Comment by t-kitamura-axel** [comment]
Thank you for advice.
But., still recognized json as string.

- runn book yaml

```
desc: xxxx xxxxx xxxx
vars:
  xxxxx_req:
    - "../../json/req/200/normal1.json"
    - "../../json/req/200/normal2.json"
  xxxxx_res:
    - "do some magic"
    - "do some magic"
steps:
  normal:
    desc:  xxxx xxxx xxxx xxxx
    loop:
      count: len(vars.xxxxx_req)
    req:
      /xxx/xxx/xx/xxxxx:
        post:
          headers:
            accept: "{{ vars.header.accept }}"
            Content-Type: "{{ vars.header.content_type }}"
            Host: "{{ vars.header.host }}"
            X-API-KEY: "{{ vars.header.x_api_key }}"
          body:
            application/json: "json://{{ vars.xxxxx_req[i] }}"
    test: steps.normal.res.status == 200
      && steps.normal.res.body contains vars.xxxxx_res[i]
```


Avobe yaml is imported one.
Bellow yaml is importing yaml.
In order to be recognized json in loop, do I declare json list vars in importing yaml?
If so, it might be hard a little in my usecase. 
Because test case is many,   vars will be fat. Also it is hard to find certain test case vars in importing one.
Than that, I want to summarize vars to imported yaml.
I think that way is view better for seeing the details individually.

importing runn book yaml (root)

```
  xxx xxx xx:
    desc: xxx xxxx xxxx
    include:I 
      path: xx/xx/xxx/yamls/200/normal.yaml
      vars:
        header:
          accept: "{{ vars.header.accept }}"
          content_type: "{{ vars.header.content_type }}"
          host: "{{ vars.header.host }}"
          x_api_key: "{{ vars.header.x_api_key }}" 

```

**Comment by k1LoW** [comment]
fmm...

I do not know what you want to achieve.
If possible I would be glad to get the smallest example I can try.
You shouldn't need to have a test server by using the API on httpbin.org or github.com.

**Comment by k2tzumi** [comment]
> In order to be recognized json in loop, do I declare json list vars in importing yaml?

You can manage the path of the json file in the runbook from which you are importing

* root.yaml
```yaml
desc: xxxx xxxxx xxxx
vars:
  xxxxx_req:
    - "../../json/req/200/normal1.json"
    - "../../json/req/200/normal2.json"
  xxxxx_res:
    - "do some magic"
    - "do some magic"
 headers:
   accept: 'application/json'
   Content-Type: 'application/json'
   Host: 'xxxx'
   X-API-KEY: 'xxxxxx'

steps:
  normal:
    desc:  xxxx xxxx xxxx xxxx
    loop:
      count: len(vars.xxxxx_req)
    include:
      path: xx/xx/xxx/yamls/200/normal.yaml
      vars:
        headers: '{{ vars.headers }}'
        request: 'json://{{ vars.xxxxx_req[i]}}'
        response: '{{ vars. xxxxx_res[i] }}'
```

* xx/xx/xxx/yamls/200/normal.yaml
```yaml
vars:
  request: null
  response: null
  headers: null

steps:
  normal:
    desc:  xxxx xxxx xxxx xxxx
    req:
      /xxx/xxx/xx/xxxxx:
        post:
          headers: "{{ vars.headers }}"
          body:
            application/json: "{{ vars.request }}"
    test: steps.normal.res.status == 200
      && steps.normal.res.body contains vars.response
```

**Comment by t-kitamura-axel** [comment]
I want to recognize json as json in impoted yaml.
In `runn`, Is it  impossible to bellow yaml ?


```
desc: xxxx xxxxx xxxx
vars:
  xxxxx_req: <- json list
    - "json://../../json/req/200/normal1.json"
    - "json://../../json/req/200/normal2.json"
  xxxxx_res:
    - "do some magic"
    - "do some magic"
steps:
  normal:
    desc:  xxxx xxxx xxxx xxxx
    loop:
      count: len(vars.xxxxx_req)
    req:
      /xxx/xxx/xx/xxxxx:
        post:
          headers:
            accept: "{{ vars.header.accept }}"
            Content-Type: "{{ vars.header.content_type }}"
            Host: "{{ vars.header.host }}"
            X-API-KEY: "{{ vars.header.x_api_key }}"  <- json  as json
          body:
            application/json: "json://{{ vars.xxxxx_req[i] }}"
    test: steps.normal.res.status == 200
      && steps.normal.res.body contains vars.xxxxx_res[i]
```

**Comment by k1LoW** [comment]
> In runn, Is it impossible to make bellow yaml ?

No, it cannot.
The `json://` scheme only works for root in the `vars:` section.

**Comment by k2tzumi** [comment]
> I want to recognize json as json in impoted yaml.

Do you want the list of json file paths in the root runbook to be specified in the vars of the include and expanded as a json request?

I would be able to give you better advice if I could get a more concrete image of the test you want to achieve.

**Comment by t-kitamura-axel** [comment]
What  is `include.vars` ?

```
The json:// scheme only works for root in the vars: section ( or include.vars: ). 
```

With this, the root yaml vars will be fat, right?
if many test is written in root yaml.   I think root yaml vars is fat.  

bellow root yaml fat example

```
desc: xxxx xxxxx xxxx
vars:
  xxxxx_req:
    - "../../json/req/200/normal1.json"
    - "../../json/req/200/normal2.json"
  xxxxx_res:
    - "do some magic"
    - "do some magic"
  yyyyy_req:
    - "../../json/req/200/normal1.json"
    - "../../json/req/200/normal2.json"
  yyyy_res:
    - "do some magic"
    - "do some magic"
 zzzz_req:
    - "../../json/req/200/normal1.json"
    - "../../json/req/200/normal2.json"
  zzzz_res:
    - "do some magic"
    - "do some magic"
  wwww_req:
    - "../../json/req/200/normal1.json"
    - "../../json/req/200/normal2.json"
  wwww_res:
    - "do some magic"
    - "do some magic"
   .
   .
   .
   .
 headers:
   accept: 'application/json'
   Content-Type: 'application/json'
   Host: 'xxxx'
   X-API-KEY: 'xxxxxx'

steps:
  normal-x:
    desc:  xxxx xxxx xxxx xxxx
    loop:
      count: len(vars.xxxxx_req)
    include:
      path: xx/xx/xxx/yamls/200/normal.yaml
      vars:
        headers: '{{ vars.headers }}'
        request: 'json://{{ vars.xxxx_req[i]}}'
        response: '{{ vars. xxxx_res[i] }}'
  normal-y:
    desc:  xxxx xxxx xxxx xxxx
    loop:
      count: len(vars.yyyyy_req)
    include:
      path: xx/xx/xxx/yamls/200/normal.yaml
      vars:
        headers: '{{ vars.headers }}'
        request: 'json://{{ vars.yyyy_req[i]}}'
        response: '{{ vars. yyyy_res[i] }}'
  normal-z:
    desc:  xxxx xxxx xxxx xxxx
    loop:
      count: len(vars.zzzz_req)
    include:
      path: xx/xx/xxx/yamls/200/normal.yaml
      vars:
        headers: '{{ vars.headers }}'
        request: 'json://{{ vars.zzzz_req[i]}}'
        response: '{{ vars. zzzz_res[i] }}'

 normal-z:
    desc:  xxxx xxxx xxxx xxxx
    loop:
      count: len(vars.wwwww_req)
    include:
      path: xx/xx/xxx/yamls/200/normal.yaml
      vars:
        headers: '{{ vars.headers }}'
        request: 'json://{{ vars.wwww_req[i]}}'
        response: '{{ vars. wwww_res[i] }}'
 .
.
.
.
```

**Comment by k1LoW** [comment]
> What is include.vars ?

[`vars:` section of include runner](https://github.com/k1LoW/runn#include-runner-include-other-runbook).

**Comment by k1LoW** [comment]
How about `xxxxx_req` and `yyyyy_req` and `zzzz_req` and `wwww_req` and all responses in one JSON?

```yaml
desc: xxxx xxxxx xxxx
vars:
  reqres: "json://../../json/reqres.json"
   .
   .
   .
 headers:
   accept: 'application/json'
   Content-Type: 'application/json'
   Host: 'xxxx'
   X-API-KEY: 'xxxxxx'

steps:
  normal-x:
    desc:  xxxx xxxx xxxx xxxx
    loop:
      count: len(vars.reqres.xxxxx)
    req:
      /xxx/xxx/xx/xxxxx:
        post:
          headers:
            accept: "{{ vars.header.accept }}"
            Content-Type: "{{ vars.header.content_type }}"
            Host: "{{ vars.header.host }}"
            X-API-KEY: "{{ vars.header.x_api_key }}"  
          body:
            application/json: "{{ vars.reqres.xxxxx[i].req}}"
    test: steps.normal.res.status == 200
      && steps.normal.res.body contains vars.reqres.xxxxx[i].res
.
.
.
```

> With this, the root yaml vars will be fat, right?

I don't know if this is what you want, but at least all requests and responses can be externalized to reqres.json.
