### ISSUE TITLE
http request fails when using numeric value for variable in multipart/form-data

### ISSUE THREAD

**Issue by pa-h-matsumoto** [k1LoW/runn#552]
Failed to execute 'runn' http request when trying to request API using multipart/form-data.
The problem is that the num declared in vars is a number and if I set num to a character, the 'runn' http request runs fine.
Please help me because I want to set a number to num and make the http request successful.

created yaml
```
desc: multipart/form-data test
runners:
  req: http://localhost:8080
vars:
  directory: SHARED
  num: 10
steps:
  postCard:
    req:
      /v1/card:
        post:
          body:
            multipart/form-data:
              cardImage: ../resources/card-jp.jpeg
              directory: "{{ vars.directory }}"
              num: "{{ vars.num }}"
```

error returned by runn
`
Failure/Error: http request failed on 'multipart/form-data test'.steps.postCard: invalid body: map[cardImage:../resources/card-jp.jpeg directory:SHARED num:10]
`
