### ISSUE TITLE
Access to response results during loop

### ISSUE THREAD

**Issue by k2tzumi** [k1LoW/runn#569]
For example.
```yaml
runners:
  req: https://api.example.com
steps:
  loopStep:
     loop:
      count: 10
    req:
      /odd?num={{ i }}
       get:
   referenceLoopStep:
     test: |
       steps.loopStep.loog[0].res.body.result == false  # I want to refer to the response result of each loop from another step.
       && steps.loopStep.loog[1].res.body.result == true
       && steps.loopStep.loog[2].res.body.result == false
```

**Comment by k1LoW** [comment]
Maybe `s/loog/loop/` ?

**Comment by k2tzumi** [comment]
yes. loop

**Comment by k1LoW** [comment]
The namespace `loop` is not violated by anything else, and looks good to me.

On the other hand, if we can get a syntax that allows us to assign to an array with bind runner, we may be able to substitute it.

Then we would not have to increase namespace and memory usage would be limited.

```yaml
runners:
  req: https://api.example.com
steps:
  loopStep:
     loop:
      count: 10
    req:
      /odd?num={{ i }}
       get:
    bind:
      'loop[i]' : current.res # ?????????
   referenceLoopStep:
     test: |
       loop[0].res.body.result == false  # I want to refer to the response result of each loop from another step.
       && loop[1].res.body.result == true
       && loop[2].res.body.result == false
```

But I can't imagine a good syntax.

**Comment by k2tzumi** [comment]
> if we can get a syntax that allows us to assign to an array with bind runner, we may be able to substitute it.

I thought the idea of being able to specify a variable with a variable name at the time of binding was very good. 👍

**Comment by k2tzumi** [comment]
I thought the following description would be good

```yaml
runners:
  req: https://api.example.com
steps:
  loopStep:
     loop:
      count: 10
    req:
      /odd?num={{ i }}
       get:
    bind:
      "foo[]": current.res.body.foo 
```
