### ISSUE TITLE
The notFollowRedirect option does not work. 

### ISSUE THREAD

**Issue by Hyuga-Tsukui** [k1LoW/runn#609]
When defining the runn.Option at the top level with the option set to 0, the notFollowRedirect defined within the book is ignored. Is this by design?

```go
opts := []runn.Option{
		runn.T(t),
		runn.Runner("req", ts.URL), // define.
}
```

```yaml
desc: Test using HTTP (notFollowRedirect)
runners:
  req:
    notFollowRedirect: true # is ignored.
steps:
  redirect:
    desc: Get /redirect
    req:
      /:
        get:
          body:
            application/json:
              null
    test: |
      current.res.status == 302 && current.res.headers["Location"][0] == "http://example.com"
```

The following is the actual execution result.

```
-----END HTTP RESPONSE-----
Run 'test' on 'Test using HTTP (notFollowRedirect)'.steps.redirect
    operator.go:1366: test failed on 'Test using HTTP (notFollowRedirect)'.steps.redirect 'Get /redirect': condition is not true
        
        Condition:
          current.res.status == 302 && current.res.headers["Location"][0] == "http://example.com"
          │
          ├── current.res.status => 200
          ├── 302 => 302
          ├── current.res.headers.Location[0] => ?
          └── "http://example.com" => "http://example.com"
          
        
--- FAIL: TestServerRedirect (0.25s)
```

Intuitively, I thought that options set at a deeper level would take precedence. In fact, options like "endpoint" seem to work that way.
