### ISSUE TITLE
Is it possible to treat the stdout as an integer instead of a string?

### ISSUE THREAD

**Issue by ap-gun** [k1LoW/runn#621]
I would like to treat the stdout value of the previous step as an integer, not a string. Is it possible to do this?
```
steps:
  -
    exec:
      # generate random number
      command: echo -n `seq 1 100000 | sort -R | head -n 1`
  -
    req:
      /sample:
        post:
          body:
            application/json:
              id: "{{ steps[0].stdout }}" # require integer but the actual value passed is string
```

Alternatively, is there a way to get a random number using built-in features?

**Comment by k1LoW** [comment]
> I would like to treat the stdout value of the previous step as an integer, not a string. Is it possible to do this?

You can use `int()`.

```yaml
desc: Test desc
runners:
  req: https://httpbin.org
steps:
  -
    exec:
      # generate random number
      command: |
        echo `seq 1 100000 | sort -R | head -n 1`

  -
    req:
      /anything:
        post:
          body:
            application/json:
              id: "{{ int(steps[0].stdout) }}"
    dump:
      current.res.body
```

```console
$ runn run tmp.yml
{
  "args": {},
  "data": "{\"id\":11211}",
  "files": {},
  "form": {},
  "headers": {
    "Accept-Encoding": "gzip",
    "Content-Length": "12",
    "Content-Type": "application/json",
    "Host": "httpbin.org",
    "User-Agent": "Go-http-client/2.0",
    "X-Amzn-Trace-Id": "Root=1-651e7fa5-777242411278879e43a4d581"
  },
  "json": {
    "id": 11211
  },
  "method": "POST",
  "origin": "123.198.33.120",
  "url": "https://httpbin.org/anything"
}
.

1 scenario, 0 skipped, 0 failures
```

> Alternatively, is there a way to get a random number using built-in features?

You can use `faker.IntRange(1, 100000)`

https://pkg.go.dev/github.com/k1LoW/runn@v0.83.1/builtin#Faker.IntRange
