### ISSUE TITLE
I want to work with an escaped json string in the request body

### ISSUE THREAD

**Issue by ap-gun** [k1LoW/runn#624]
I receive a json string in one response with double quotes already escaped. I'd like to use this string in the another request body, but when I specify this string as a parameter, it gets converted into json. Is there a way to avoid this or re-escape the json?

```
runners:
  req: http://localhost:8080
steps:
  - req:
    /foo:
      get:
        body: null
  - req:
    /foo:
      post:
        body:
          application/json:
            message: "{{ steps[0].res.body.message }}"
```

```
Run steps[0]
-----START HTTP RESPONSE-----
{"message":"{\"key\":{\"inner\":\"aaaa\"}}"}
-----END HTTP RESPONSE-----

...

Run steps[1]
-----START HTTP REQUEST-----
{"message":{"key":{"inner":"aaaa"}}}
But I need
{"message":"{\"key\":{\"inner\":\"aaaa\"}}"}
-----END HTTP REQUEST-----
```

**Comment by k1LoW** [comment]
You can use `message: '"{{ steps[0].res.body.message }}"'` ( Wrap using `'` ). 

```yaml
desc: Test desc
runners:
  req: https://httpbin.org
steps:
  -
    req:
      /anything:
        post:
          body:
            application/json:
              id: hello
  -
    req:
      /anything:
        post:
          body:
            application/json:
              message: '"{{ previous.res.body }}"'
    dump:
      current.res.body.json.message
```

```console
$ runn run tmp.yml
\"{"args":{},"data":"{\"id\":\"hello\"}","files":{},"form":{},"headers":{"Accept-Encoding":"gzip","Content-Length":"14","Content-Type":"application/json","Host":"httpbin.org","User-Agent":"Go-http-client/2.0","X-Amzn-Trace-Id":"Root=1-651f7b37-1dd0807d301d3429573a3221"},"json":{"id":"hello"},"method":"POST","origin":"123.198.33.120","url":"https://httpbin.org/anything"}\"
.

1 scenario, 0 skipped, 0 failures
```
