### ISSUE TITLE
Allow variables to be embedded in the desc section

### ISSUE THREAD

**Issue by k2tzumi** [k1LoW/runn#672]
```yaml
vars:
  username: "foo"
steps:
- desc: "Retrieve a list of {{vars.username}} articles"
  req:
    /api/articles?username={{ vars.username }}&count=96&order=latest:
      get:
        body:
          application/json: null
```
