### ISSUE TITLE
How can I loop over multiple steps?

### ISSUE THREAD

**Issue by mizuki0906** [k1LoW/runn#687]
Hi,
Thank you for such a great.

But I'm having trouble because there are things I can't do.
I want to loop across multiple steps.
For example,
```
runners:
  req:
    endpoint: "${ENDPOINT}"
    openapi3: "${OPENAPI_FILE_PATH}"
vars:
  request1:
    - "json://req1_1.json"
    - "json://req1_2.json"
  request1:
    - "json://req2_1.json.template"
    - "json://req2_2.json.template"
loop:
  count: 2
steps:
  step1:
    desc: "step1"
    include:
      path: "step1.yml"
      vars:
        requestJson: "{{ vars.request1[i] }}"
  step2:
    desc: "step2"
    include:
      path: "step2.yml"
      vars:
        requestJson: "{{ vars.request2[i] }}"
```
```
- First time exec
  step1: req1_1.json
  step2: req2_1.json.template

- Second time exec
  step1: req1_2.json
  step2: req2_2.json.template
```

And also,
If possible, I would like to dynamically overwrite the json file.

For example, req2_1.json.template
```
{
  "id": "{{.steps.step1.res.body.id}}",
  "name": "xxx",,,
}
```

Is it not possible to do like this?
 please, help me.

**Comment by k1LoW** [comment]
The index of the root loop of the runbook cannot be retrieved.

A new runbook for the loop will achieve what you want to do.

```yaml
runners:
  req:
    endpoint: "${ENDPOINT}"
    openapi3: "${OPENAPI_FILE_PATH}"
vars:
  request1:
    - "json://req1_1.json"
    - "json://req1_2.json"
  request2:
    - "json://req2_1.json.template"
    - "json://req2_2.json.template"
steps:
  forloop:
    loop: 2
    include:
      path: internal.yml
      vars:
        request1: vars.request1[i]
        request2: vars.request2[i]
```

```yaml
# internal.yml
desc: internal
steps:
  step1:
    desc: "step1"
    include:
      path: "step1.yml"
      vars:
        requestJson: "{{ vars.request1 }}"
  step2:
    desc: "step2"
    include:
      path: "step2.yml"
      vars:
        requestJson: "{{ vars.request2 }}"
```
