### ISSUE TITLE
spanner: code = "InvalidArgument", desc = "invalid session pool"

### ISSUE THREAD

**Issue by h6ah4i** [k1LoW/runn#710]
Hi. I noticed an issue with the Spanner database integration of runn.

The runn implementation creates database client object for each runbooks to make the database connections are not shared between runbooks. However, the [go-sql-spanner driver reuses the same connection internally](https://github.com/googleapis/go-sql-spanner/blob/b56bfa8df549780852674f178a1c06f56f0f4c45/driver.go#L183) when the specified DSN is identical.

## Actual behavior
An error occurs when trying to use the same Spanner database in multiple runbooks.

```bash
❯ SPANNER_EMULATOR_HOST=localhost:9010 runn run  spanner_1.yml spanner_2.yml
..

1) spanner_2.yml 0e14c3d7ebcfe48aa13335c5d31fbd1681e0f4fb
  Failure/Error: db query failed on "Test using Spanner".steps[0]: spanner: code = "InvalidArgument", desc = "invalid session pool"
  Failure step (spanner_2.yml):
  5   - db:
  6       query: SELECT 1;


2 scenarios, 0 skipped, 1 failure
```

## Reproduction

1. Launch Spanner emulator
    ```bash
    docker run -p 9010:9010 -p 9020:9020 gcr.io/cloud-spanner-emulator/emulator
    ```
2. Setup the database
    ```bash
    docker run -eSPANNER_EMULATOR_HOST=localhost:9010 --network=host google/cloud-sdk:slim bash -c 'gcloud config configurations create emulator && gcloud config set auth/disable_credentials true && gcloud config set project test-project && gcloud config set api_endpoint_overrides/spanner http://localhost:9020/ && gcloud spanner instances create test-instance --config=emulator-config --description="Test Instance" --nodes=1 && gcloud spanner databases create test-database --instance=test-instance'
    ```
3. runn run
    ```bash
    SPANNER_EMULATOR_HOST=localhost:9010 runn run  spanner_1.yml spanner_2.yml
    ```

---

#### spanner_1.yml
```yaml
desc: Test using Spanner
runners:
  db: spanner://test-project/test-instance/test-database
steps:
  - db:
      query: SELECT 1;
```

#### spanner_2.yml
```yaml
desc: Test using Spanner
runners:
  db: spanner://test-project/test-instance/test-database
steps:
  - db:
      query: SELECT 1;
```
