### ISSUE TITLE
Using a variable passed from parent runner for the loop count specifier

### ISSUE THREAD

**Issue by h6ah4i** [k1LoW/runn#750]
It seems that runn does not support the following situation. I'm afraid that this might be a bug.

```bash
❯ runn run parent.yml
F

1) parent.yml 1d64130a3907ffc6d5d330a45e189ce85aa06de9
   └── included.yml
  Failure/Error: invalid count: evaluated vars.count, but got uint64(3)
  Failure step (included.yml):
  6   -
  7     dump: vars.hello
  8     loop: vars.count


1 scenario, 0 skipped, 1 failure
```

<details>
<summary>parent.yml</summary>

```yaml
steps:
-
  include:
    path: included.yml
    vars:
      hello: HELLO
      count: 3
```

</details>
<details>

<summary>included.yml</summary>

```yaml
vars:
  hello: hello
  count: 2

steps:
  -
    dump: vars.hello
    loop: vars.count
```
</details>
