### ISSUE TITLE
Is there way runn test of grpc with using "buf/validate/validate.proto" in proto ? 

### ISSUE THREAD

**Issue by mztnnrt** [k1LoW/runn#784]
#### At First

At first we want to express our appreciate this great oss, we use every day thanks. 🙏

----

#### Question

Now we want to gRPC E2E test using https://buf.build,  
But we use `buf.build/bufbuild/protovalidate` as dependency for proto validate.

<details>
<summary><code>buf.gen.yaml</code></summary>

```yaml
version: v1
managed:
  enabled: true
plugins:
  - plugin: go
    out: ../go/backend/shared/generated/proto
    opt:
      - paths=source_relative
  - plugin: connect-go
    out: ../go/backend/shared/generated/proto
    opt:
      - paths=source_relative
      - require_unimplemented_servers=false
```

</details>
<details>
<summary><code>buf.yaml</code></summary>

```yaml
version: v1
deps:
  - buf.build/googleapis/googleapis
  - buf.build/bufbuild/protovalidate # 💡 using protovalidate.
breaking:
  use:
    - FILE
lint:
  use:
    - DEFAULT
  except:
    - PACKAGE_DIRECTORY_MATCH
    - PACKAGE_VERSION_SUFFIX
  ignore: []
  rpc_allow_google_protobuf_empty_requests: true
  rpc_allow_google_protobuf_empty_responses: true
```
</details>

<details>
<summary><code>service.proto</code></summary>

```diff
syntax = "proto3";

package pingpb;
+ import "buf/validate/validate.proto";

option go_package = "github.com/path/to/generated/proto/pingpb";
import "google/protobuf/empty.proto";
import "shared/shared.proto";

service Service {
  rpc Ping(PingRequest) returns (PingResponse) {};
}

message PingRequest {
  google.protobuf.Empty empty = 1;
}

message PingResponse {
  bool backend  = 1;
}

```

</details>

If remove `import "buf/validate/validate.proto";` from above proto file, below runn command is success !

```bash
runn run ./e2e/backend/grpc.yaml --grpc-no-tls --grpc-import-path ./proto --grpc-proto ./proto/pingpb/service.proto
1 scenario, 0 skipped, 0 failures
```

But if import this `import "buf/validate/validate.proto"`, 
runn command is failure, because validate.proto: no such file or directory.

```bash
runn run ./e2e/backend/grpc.yaml --grpc-no-tls --grpc-import-path ./proto --grpc-proto ./proto/pingpb/service.proto
1) ./e2e/backend/grpc.yaml aef9bc8f868dadf4c516cc3e4a7478693555f41b
  Failure/Error: gRPC request failed on "package pingpb".steps[0]: pingpb/service.proto:4:8: 
open /Users/path/to/monorepo/proto/buf/validate/validate.proto: no such file or directory

1 scenario, 0 skipped, 1 failure
```

Is there approach, runn test with using https://buf.build dependencies ?
