### ISSUE TITLE
How to specify an absolute path to load JSON file

### ISSUE THREAD

**Issue by bearmini** [k1LoW/runn#821]
I want to use a JSON file at like `$HOME/.config/some/dir/file.json`, so I have put the absolute path for my vars section:

```
vars:
  profile: 'json:///home/user/.config/some/dir/file.json'
```
and tried to send it in a test step:

```
steps:
- req:
    /v1/foo:
      post:
        headers:
          Content-Type: application/json
        body:
          application/json: "{{ vars.profile }}"
```

but I got the following error:

```
evaluate file error: read external files error: stat home/user/.config/some/dir/file.json: no such file or directory
```

It seems that the leading `/` is removed according to the error message. 
Tried `json:////`, but the result was the same.

Relative path (like `json://../../../../../../../home/user/.config/some/dir/file.json`) worked, so I'm sure the file does exist and is readable.

How can I specify an absolute path to load JSON file?
