### ISSUE TITLE
Could not continue execute other cases after failure case

### ISSUE THREAD

**Issue by hungpk-bap** [k1LoW/runn#894]
I write API test base on the guild [runn Grpc server](https://github.com/k1LoW/runn?tab=readme-ov-file#run-n-runbooks-using-grpcserver)

I have 2 test files: 
- login_test.yml (multiple case):
```
desc: Login
vars:
  request:
    - "001-Success-request.json"
    - "002-IncorrectPassword-request.json"
    - "003-IncorrectUsername-request.json"
  response:
    - "001-Success-response.json"
    - "002-IncorrectPassword-response.json"
    - "003-IncorrectUsername-response.json"
steps:
  - loop:
      count: len(vars.request)
    include:
      path: requestBase.yml
      vars:
        request: "json://../test-data/login/{{ vars.request[i] }}"
        response: "json://../test-data/login/{{ vars.response[i] }}"
        testPath: "/login"
        testCase: "Login { vars.request[i] }}"
```
- logout_test.yml (multiple case)

1 requestBase.yml file as below:
```
runners:
  greq:
    addr: ${BASE_GRPC_URL}
    tls: false 
    protos:
      - ../../../*.proto
steps:
  - greq:
      "{{ vars.testPath }}":
        headers:
          test-case: "{{ vars.testCase }}"
        message: "{{ vars.request }}"
    test: compare(current.res.message, vars.response)
```
main_test.go
```
func TestAPI(t *testing.T) {
	flag.Parse() // Parse the flags

	err := godotenv.Load(".env")
	if err != nil {
		log.Fatal("Error loading .env file")
	}

	opts := []runn.Option{
		runn.T(t),
		runn.Debug(true),
	}

	runner, err := runn.Load(
		*testPath,
		opts...,
	)

	if err != nil {
		t.Error(err)
	}

	ctx := context.TODO()

	if err := runner.RunN(ctx); err != nil {
		t.Log(err)
	}
}
```
When I run all test. 
When case 001 login success, case 002 login failure. It stop (do not run case 003 login, although logout_test still run) 
I change: t.Fatal(err) -> t.Error(err)
purpose continue execute other case if in test_file.yml has failure case.
But it does not work. It still stop.
Could you share idea or something wrong here? Thank you very much!
