### ISSUE TITLE
Include runner ignores values after newline in variable

### ISSUE THREAD

**Issue by na3shkw** [k1LoW/runn#920]
I'm using include runner to use other runbooks. When passing variables with multiline values using `vars:`, it seems that values after newline in variable are being ignored. This can be reproduced with runn version `v0.107.1` using the following runbook and command.

**`parent.yml`**
```yaml
desc: Parent runbook
steps:
  createMessage:
    exec:
      command: |
        cat <<EOF
        1st line
        2nd line
        EOF
  printMessageParent:
    dump: steps.createMessage.stdout
  sampleStep:
    include:
      path: child.yml
      vars:
        message: "{{ steps.createMessage.stdout }}"
```

**`child.yml`**
```yaml
desc: Child runbook
vars:
  message: No message
force: true
steps:
  printMessageChild:
    dump: vars.message
  testShouldPass:
    test: vars.message == "1st line\n2nd line\n"
  testShouldFail:
    test: vars.message == "1st line"
```

Command and output result:
```shell
$ runn run --scopes run:exec --verbose parent.yml
=== Parent runbook (parent.yml)
    --- (createMessage) ... ok
1st line
2nd line

    --- (printMessageParent) ... ok
1st line
    --- (printMessageChild) ... ok
    --- (testShouldPass) ... fail
        Failure/Error: test failed on "Child runbook".steps.testShouldPass: condition is not true
        
        Condition:
          vars.message == "1st line\n2nd line\n"
          │
          ├── vars.message => "1st line"
          └── "1st line\n2nd line\n" => "1st line
              2nd line
              "
          
        Failure step (child.yml):
        8   testShouldPass:
        9     test: vars.message == "1st line\n2nd line\n"

    --- (testShouldFail) ... ok
        === Child runbook (child.yml)
            --- (testShouldFail) ... ok


1 scenario, 0 skipped, 1 failure
```

Looking at the results, it appears that `vars.message` is being interpreted as `1st line`.
